version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.2

jobs:
  deploy:
    working_directory: ~/aws-infrastructure
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: ~/aws-infrastructure
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: Deploy CloudFormation template
          command: |
            aws cloudformation deploy \
              --template-file "stacks/base.yml" \
              --stack-name "AUS-DDR-BASE-STACK" \
              --parameter-overrides \
                "DBInstanceID=ausddrdb" \
                "DBUsername=${AWS_DB_USERNAME}" \
                "DBPassword=${AWS_DB_PASSWORD}" \
              --no-fail-on-empty-changeset
      - run:
          name: Deploy Prod CloudFormation template
          command: |
            aws cloudformation deploy \
              --template-file "stacks/prod.yml" \
              --stack-name "AUS-DDR-PROD-STACK" \
              --parameter-overrides \
                "S3IAMUsername=${S3_IAM_USERNAME}" \
                "S3IAMPassword=${S3_IAM_PASSWORD}" \
              --no-fail-on-empty-changeset

workflows:
  deploy_base_infrastructure:
    jobs:
      - deploy_infrastructure:
          type: approval
      - deploy:
          context:
            - production
          requires:
            - deploy_infrastructure

