AWSTemplateFormatVersion: 2010-09-09

Description: Production infrastructure used by AUS-DDR-Events

Parameters:
  S3IAMUsername:
    Description: Username for S3 IAM User
    NoEcho: true
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: >-
      Must be 1-64 characters and match [a-zA-Z0-9]+
  S3IAMPassword:
    Description: Password for S3 IAM User
    NoEcho: true
    Type: String
    MinLength: '32'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: >-
      Must be 32-64 characters and match [a-zA-Z0-9]+

Resources:
  AusDdrAssetsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: aus-ddr-events-bucket-prod
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
            AllowedOrigins:
              - https://ausddrevents-e18b1--ausddrevents-staging-e6gg8r0y.web.app/
              - https://ausddrevents.com/
              - http://localhost:1234/
            Id: public-visibility-cors-rule
            MaxAge: 3600

  S3IAMPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: 'Allow'
          Action:
            - 's3:ListBucket'
          Resource:
            - Fn::GetAtt: AusDdrAssetsBucket.Arn
        - Effect: 'Allow'
          Action:
            - 's3:PutObject'
            - 's3:GetObject'
            - 's3:DeleteObject'
          Resource:
            - !Join
              - '/'
              - - Fn::GetAtt: AusDdrAssetsBucket.Arn
                - '*'
      PolicyName: S3ReadWrite
      Users:
        - !Ref S3IAMUser
    DependsOn:
      - S3IAMUser

  S3IAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      LoginProfile:
        Password: !Ref S3IAMPassword
        PasswordResetRequired: false
      UserName: !Ref S3IAMUsername
    DependsOn:
      - AusDdrAssetsBucket

Outputs:
    websiteUrl:
      Value:
        Fn::GetAtt: AusDdrAssetsBucket.WebsiteURL
      Export:
        Name: AusDdrAssetsBucketAddr
    httpsWebsiteUrl:
      Value: !Join
        - ''
        - - 'https://'
          - Fn::GetAtt: AusDdrAssetsBucket.DomainName
      Export:
        Name: HttpsAusDdrAssetsBucketAddr
