AWSTemplateFormatVersion: 2010-09-09

Description: Production infrastructure used by AUS-DDR-Events

Resources:
  AusDdrAssetsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: aus-ddr-events-bucket-prod
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
            AllowedOrigins:
              - https://ausddrevents-e18b1--ausddrevents-staging-e6gg8r0y.web.app/
              - https://ausddrevents.com/
              - http://localhost:1234/
            Id: public-visibility-cors-rule
            MaxAge: 3600
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: false

Outputs:
    websiteUrl:
      Value:
        Fn::GetAtt: AusDdrAssetsBucket.WebsiteURL
      Export:
        Name: AusDdrAssetsBucketAddr

