AWSTemplateFormatVersion: 2010-09-09

Description: Production infrastructure used by AUS-DDR-Events

Parameters:
  S3IAMUsername:
    Description: Username for S3 IAM User
    NoEcho: true
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: >-
      Must be 1-64 characters and match [a-zA-Z0-9]+

Resources:
  AusDdrAssetsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: aus-ddr-events-bucket-prod
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
            AllowedOrigins:
              - https://ausddrevents-e18b1--ausddrevents-staging-e6gg8r0y.web.app/
              - https://ausddrevents.com/
              - http://localhost:1234/
            Id: public-visibility-cors-rule
            MaxAge: 3600

  S3IAMPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: AllowViewingOfBucket
          Effect: 'Allow'
          Action:
            - 's3:ListBucket'
          Resource:
            - Fn::GetAtt: AusDdrAssetsBucket.Arn
        - Sid: EnableBucketActions
          Effect: 'Allow'
          Action:
            - 's3:PutObject'
            - 's3:GetObject'
            - 's3:DeleteObject'
            - 's3:*Object*'
          Resource:
            - !Join
              - '/'
              - - Fn::GetAtt: AusDdrAssetsBucket.Arn
                - '*'
      PolicyName: S3ReadWrite
      Users:
        - !Ref S3IAMUser
    DependsOn:
      - S3IAMUser

  S3IAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Ref S3IAMUsername
    DependsOn:
      - AusDdrAssetsBucket


  ecsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: ecsManagementPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Resource: !GetAtt ecsIAMUser.Arn
                Action: 
                  - ec2:DescribeTags
                  - ecs:CreateCluster
                  - ecs:DeregisterContainerInstance
                  - ecs:DiscoverPollEndpoint
                  - ecs:Poll
                  - ecs:RegisterContainerInstance
                  - ecs:StartTelemetrySession
                  - ecs:UpdateContainerInstancesState
                  - ecs:Submit*
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvent
    DependsOn:
      - ecsIAMUser


  ecsIAMUser:
    Type: 'AWS::IAM::User'

Outputs:
    websiteUrl:
      Value:
        Fn::GetAtt: AusDdrAssetsBucket.WebsiteURL
      Export:
        Name: AusDdrAssetsBucketAddr
    httpsWebsiteUrl:
      Value: !Join
        - ''
        - - 'https://'
          - Fn::GetAtt: AusDdrAssetsBucket.DomainName
      Export:
        Name: HttpsAusDdrAssetsBucketAddr
